CREATE TABLE CLASSMATES (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

INSERT INTO CLASSMATES VALUES (01, 'Kolyan', 30, 'Moscow');
INSERT INTO CLASSMATES VALUES (02, 'Viktor', 17, 'Moscow');
INSERT INTO CLASSMATES VALUES (03, 'Katya', 40, 'Moscow');
INSERT INTO CLASSMATES VALUES (04, 'Piotr', 18, 'Doomsdey');
INSERT INTO CLASSMATES VALUES (05, 'Fiodor', 43, 'Perm');
INSERT INTO CLASSMATES VALUES (06, 'Olga', 20, 'Pereslavly');
INSERT INTO CLASSMATES VALUES (07, 'Sergyy', 25, 'Moscow');
INSERT INTO CLASSMATES VALUES (08, 'Fiofan', 32, 'Vladimir');
INSERT INTO CLASSMATES VALUES (09, 'Masha', 15, 'Moscow');

SELECT name FROM CLASSMATES WHERE age > 18 AND age< 40 AND address = 'Moscow';